version: '3.7'

services:
  consul:
    image: consul:latest
    container_name: consul_dev
    restart: always
    ports:
      - "8500:8500"
    command: >
      agent -dev
      -client=0.0.0.0
      -ui
      -data-dir=/consul/data
    volumes:
      - ./config.local.json:/consul/config.json
    networks:
      - bookify_networks

  db:
    container_name: bookify_mysql
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3309:3306"
    volumes:
      - bookify_db:/var/lib/mysql:rw
    environment:
      - MYSQL_USER=bookify_user
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=bookify
      - MYSQL_ROOT_PASSWORD=12345678
    tty: true
    networks:
      - bookify_networks

  bookify:
    container_name: bookify
    build:
      context: .
    ports:
      - "8080:8080"
    command: serve  # make `serve` into `seed` or `seed --truncate=true` if anyone want to run the seeder
    volumes:
      - ./:/project
    environment:
      - CONSUL_URL=consul_dev:8500
      - CONSUL_PATH=bookify
    tty: true
    depends_on:
      - consul
      - db
    networks:
      - bookify_networks
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  bookify_networks:
    name: bookify_networks
    driver: bridge

volumes:
  bookify_db:
    name: bookifydb-data