name: Update Latest Tag

on:
  push:
    branches:
      - master

jobs:
  update_latest_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Clone bookify repo
        uses: actions/checkout@v3
        with:
          repository: rezwanul-haque/bookify
          ssh-key: ${{ secrets.BOOKIFY_PRIVATE }}
          path: bookify
          ref: develop

      - name : Update bookify repo
        run: |
          cd bookify/
          git config --global user.email bot.rezwanul-haque.io
          git config --global user.name "Bookify Actions Bot"
          TAG=$(git describe --abbrev=0 --tags)
          echo "TAG=$TAG" >> latest_tag.txt
          git add latest_tag.txt
          git commit -m "Update latest_tag.txt with $TAG"
          git push origin develop
